config/routes.rb
Rails.application.routes.draw do
  root 'enquiries#show'
  resource :enquiries, only: %i(show update)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
  MARKETS = %w(IOT-BTC ETH-BTC LTC-BTC ETH-EUR BTC-EUR BCH-BTC ETH-BTC LTC-BTC ETH-EUR BTC-EUR BCH-BTC)

  validates :market, presence: true, inclusion: { in: MARKETS }

  validates :buy_count,
    presence: { message: 'Number of orders to sell should be specified' },
    unless: -> { sell_count.present? }

  validates :sell_count,
    presence: { message: 'Number of orders to buy should be specified' },
    unless: -> { buy_count.present? }

  validates :buy_percent, :spend_amount,
    presence: { message: 'Please specify buy percent and total amount to spend'},
    if: -> { buy_count.present? }

  validates :sell_percent, :sell_amount,
    presence: { message: 'Please specify sell percent and total amount of coins to sell'},
    if: -> { sell_count.present? }

  def orders_count
    { buy: buy_count, sell: sell_count }
  end

  def total_count
    buy_count + sell_count
  end
end

app/models/market_price.rb
class MarketPrice < ApplicationRecord
  def value_for(type:)
    public_send "#{type}_value"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  def show
    @enquiry = Enquiry.first || Enquiry.new
  end

  def update
    @enquiry = Enquiry.first || Enquiry.new

    result = UpdateEnquiry.call(enquiry: @enquiry, attributes: permitted_attributes)
    flash.replace(result.flash)

    render :show
  end

  private

  def permitted_attributes
    params.require(:enquiry).
      permit(:market, :buy_count, :sell_count, :buy_percent, :sell_percent, :spend_amount, :sell_amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
  def markets
    Enquiry::MARKETS.map { |market| [market, market] }
  end

  def open_orders(options = {})
    @open_orders ||= ApiClient.new.my_orders(status: :open)['data'].group_by do |order|
      order['order_type']
    end
  end
end

app/views/enquiries/show.haml
.container
  .form
    - if flash.any?
      - flash.each do |k, v|
        .message{class: k}=v

    = form_for @enquiry, method: :put, url: enquiries_path do |f|
      %fieldset
        %legend Bot Options
        .form-item
          = f.label 'Specify market'
          = f.select :market, markets
        .form-item
          = f.label 'How many buy orders to create?'
          = f.text_field :buy_count
        .form-item
          = f.label 'How many sell orders to create?'
          = f.text_field :sell_count
        .form-item
          = f.label 'How much lower the buy price should be?'
          = f.text_field :buy_percent
        .form-item
          = f.label 'How much higher in % the sell price should be?'
          = f.text_field :sell_percent
        .form-item
          = f.label 'How much you want to spend on purchase in total?'
          = f.text_field :spend_amount
        .form-item
          = f.label 'How much you want to sell in total?'
          = f.text_field :sell_amount
        .form-item
          = f.submit class: 'button w100'
  .labels-wrapper
    .labels
      #buy_orders
        .label.badge.outline.black.order__labels= "You have #{open_orders['buy'].to_h.count} buy orders"
        - open_orders['buy'].each do |order|
          .message.order__message
            = "market: #{order['market']}"
            %br
            = "price: #{order['price']}"
            %br
            = "size: #{order['size']}"
      #sell_orders
        .label.badge.outline.focus.order__labels= "You have #{open_orders['sell'].to_h.count} sell orders"
        - open_orders['sell'].each do |order|
          .message.order__message
            = "market: #{order['market']}"
            %br
            = "price: #{order['price']}"
            %br
            = "size: #{order['size']}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FalconecoinBot</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/kube/6.5.2/css/kube.min.css">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>